# Sample configuration file for quot

# Image reading and filtering settings
[filter]
    start = 0
    method = "identity"
    chunk_size = 100

# Spot detection settings
[detect]
    method = "llr"
    k = 1.0
    w = 9
    t = 18.0

# Subpixel localization settings
[localize]
    method = 'ls_int_gaussian'
    window_size = 9
    sigma = 1.0
    ridge = 0.001
    max_iter = 10
    damp = 0.3

# Tracking settings
[track]
    method = 'euclidean'
    pixel_size_um = 0.183
    frame_interval = 0.01048
    search_radius = 2.5
    max_blinks = 0
    min_I0 = 0.0
    scale = 7.0
