name: quot pip tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    # graphics libraries required for running pyqtgraph in this Docker container
    - name: Install libgl1-mesa-dev
      run: |
        sudo apt-get install -y libgl1-mesa-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install -e .
    - name: Test with pytest
      run: |
        pytest

  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    # graphics libraries required for running pyqtgraph in this Docker container
    # - name: Install libgl1-mesa-dev
    #   run: |
    #     sudo apt-get install -y libgl1-mesa-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install -e .
    - name: Test with pytest
      run: |
        pytest
