name: quot-tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Initialize conda
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda init
        source ~/.bashrc
        conda env create -f quot_env.yml
        conda activate quot_env
        # conda env update --file quot_env.yml --name base
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
