name: quot pip tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    # - name: Install libGL1
    #   run: |
    #     sudo apt-get install -y libgl1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        echo "which python: $(which python)"
        echo "python --version $(python --version)"
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install opencv-python-headless
        echo "which pytest: $(which pytest)"
        python -m pip install -e .
        echo "python -c 'import PySide6; print(PySide6.__file__)': $(python -c 'import PySide6; print(PySide6.__file__)')"
    - name: Test with pytest
      run: |
        pytest

